import PageBanner from "@/app-ui/PageBanner/PageBanner";
import VideosLayout from "@/app-ui/VideosLayout/VideosLayout";

const Page = () => {
  return (
    <div className="videos_wrapper">
      <PageBanner title="Videos" />
      <VideosLayout />
    </div>
  );
};

export default Page;

export const metadata = {
  title: "Videos | Mobilez Market",
  description: "Generated by create next app",
};