import ContactForm from "@/app-ui/ContactForm/ContactForm";
import PageBanner from "@/app-ui/PageBanner/PageBanner";
import SignupBanner from "@/app-ui/SignupBanner/SignupBanner";
import { GoMail } from "react-icons/go";
import { GrLocation } from "react-icons/gr";

const Page = () => {
  return (
    <div className="contact_wrap">
      <PageBanner title="Contact" />
      <div className="contact_form_wrap">
        <div className="content_wrap">
          <div className="form_wrap">
            <div className="form_cols">
              <ContactForm/>

            </div>
            <div className="form_cols for_details">
              <div className="content">
                <h3>Address</h3>
                <p>
                  Your email address will not be published. Required fields are
                  marked *
                </p>
                <ul>
                  <li>
                    <GrLocation /> DHA Karahi, Pakistan
                  </li>
                  <li>
                    <GoMail />
                    <div>
                      <a href="">info@mobilezmarket.com</a>
                      <a href="">support@mobilezmarket.com</a>
                    </div>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <SignupBanner />
      </div>
    </div>
  );
};

export default Page;

export const metadata = {
  title: "Contact | Mobilez Market",
  description: "Generated by create next app",
};
