import PageBanner from "@/app-ui/PageBanner/PageBanner";
import ProductCard from "@/app-ui/ProductCard/ProductCard";
import StyledButton from "@/app-ui/StyledButton/StyledButton";
import React from "react";

const Page = () => {
  return (
    <div className="about_wrap">
      <PageBanner title="About Us" currentPage="about" />
      <div className="content_wrap">

      
      <p>
      Mobilez Market is Pakistan’s #1 web portal for mobile phones that could provide information about various brands, models, features, prices, and reviews of mobile phones available in the market. It also offers the services to upload ad advertisements of your devices such as Mobile phones, Tablets, and Smart Watches for which you would want to find a buyer.
      </p>
      <p>
      It is not only a hub where buyers and sellers can interact, but it is also a comprehensive Mobile Phone portal with a forum dedicated to all discussions related to Mobile Phones and a blog that keeps the users up to date with the latest happenings in the Mobile Phone industry of Pakistan and the world at large.
      </p>
      <p>
      At Mobilez Market we believe that we have to provide our visitors with the best online experience and this is what our mission speaks of - to revolutionize and continuously add value to the way people buy and sell Mobile Phones online, in Pakistan. We aim to provide our users with the most comprehensive Mobile Phones knowledge concerning Pakistan and the world alike and help them develop a sense of belonging in the Mobile Phone Industry
      </p>
      </div>
    </div>
  );
};

export default Page;


export const metadata = {
  title: "About | Mobilez Market",
  description: "Generated by create next app",
};