import RootLayer from "@/app-ui/RootLayer/RootLayer";
import "react-image-gallery/styles/scss/image-gallery.scss";
import "swiper/css";
import "../styles/index.scss";
import 'swiper/css/pagination';


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <RootLayer>      
          <div id="_layout">{children}</div>       
        </RootLayer>
      </body>
    </html>
  );
}
