import RootLayer from "@/app-ui/RootLayer/RootLayer";
import "react-image-gallery/styles/scss/image-gallery.scss";
import "swiper/css";
import "../styles/index.scss";
import "swiper/css/pagination";
import { GoogleOAuthProvider } from "@react-oauth/google";
import { SpeedInsights } from "@vercel/speed-insights/next"
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <body className={inter.className}>
        <GoogleOAuthProvider clientId="85457123059-rcs2j4u7b73qndp2fjs8gn56j3m66vu4.apps.googleusercontent.com">
          <RootLayer>
            <div id="_layout">{children}</div>
            <SpeedInsights />
          </RootLayer>
        </GoogleOAuthProvider>
      <script
      
        type="text/javascript"
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDhs33Zqv1-a7XcZkEWKvJNh10oWlVYyO8&libraries=places"
      ></script>
      </body>
    </html>
  );
}


export const metadata = {
  title: "Mobilez Market",
  description: "Generated by create next",
};