import "../styles/index.scss";
import "swiper/css";
import Navbar from "@/app-ui/Navbar/Navbar";
import Footer from "@/app-ui/Footer/Footer";
import RootLayer from "@/app-ui/RootLayer/RootLayer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <RootLayer>      
          <div id="_layout">{children}</div>       
        </RootLayer>
      </body>
    </html>
  );
}
